spring:
  application:
    name: measurement-app
  datasource:
    url: jdbc:postgresql://localhost:5432/measurement-app
    username: postgres
    password: pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  cache:
    cache-names: region-city-matching
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterAccess=10m

external-api:
  region:
    url:
