spring:
  application:
    name: measurement-app
  datasource:
    url: jdbc:postgresql://localhost:5432/measurement-app
    username: postgres
    password: pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

external-api:
  region:
    url:
